In [5]:
import torch
import numpy as np

### data로 부터 직접(directly) tensor 생성하기

In [8]:
# data로 부터 직접(directly) tensor 생성하기
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


### **Numpy 배열로부터 생성하기**


##### tensor를 Numpy 배열로 변환하기 /  Numpy 배열을  tensor로 변환하기

In [19]:
# Numpy 배열로부터 생성하기
np_array = np.array(data) # data == array
x_np = torch.from_numpy(np_array)
print(x_np)

# 반대 과정 (Numpy 변환(bridge))
# -----------------------------------------------------------
# tensor를 Numpy 배열로 변환하기
t = torch.ones(5) # tensor
print(f"t: {t}")
n = t.numpy()    # tensor to numpy : tensor.numpy()
print(f"n: {n}")


t.add_(1) # tensor.add_(x) = 모든 value에 x를 더함.

# tensor의 변경 사항이 Numpy 배열에 반영됨.  
print(f"t: {t}")
print(f"n: {n}")

# -----------------------------------------------------------
# Numpy 배열을 tensor로 변환하기
n = np.ones(5)
t = torch.from_numpy(n)
print(f"t: {t}")
print(f"n: {n}")

np.add(n, 1, out=n) # np.add(array, x, out=array) : array의 모든 value에 x를 더해 out으로 array로 출력함.

# Numpy 배열의 변경사항이 Tensor에 반영됨.
print(f"t: {t}")
print(f"n: {n}")


tensor([[1, 2],
        [3, 4]])
t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]
t: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [20]:
# tensor로 부터 생성하기
# 명시적으로 override하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape),자료형(datatype))을 유지함.
x_ones =torch.ones_like(x_data)                     # x_data의 속성을 유지함.
print(f"ones Tensor: \n{x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씀.
print(f"Random Tensor: \n {x_rand} \n")


ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8357, 0.8747],
        [0.2665, 0.8162]]) 



In [23]:
# 무작위(random) 또는 상수(constant) 값을 사용하기
shape =(2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones_Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8691, 0.2787, 0.7423],
        [0.5484, 0.4887, 0.8274]])

Ones_Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [24]:
# tensor의 속성(Attribute)

# tensor의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냄.

tensor = torch.rand(3,5)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}") # default FP32
print(f"Device tensor is stored on: {tensor.device}") # default = cpu

Shape of tensor: torch.Size([3, 5])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [25]:
# tensor operation

# 전치 (transposing), 인덱싱(indexing), 슬라이싱(slicing)  등등 100가지 이상의 tensor 연산을 확인 가능.
# GPU에서 실행 가능

if torch.cuda.is_available():
     tensor = tensor.to('cuda')
     print(f"Device tensor is stored on: {tensor.device}") 

Device tensor is stored on: cuda:0


In [26]:
# Numpy식의 표준 indexing slicing
tensor = torch.ones(4,4)
tensor[:,1] = 0 # 2차원에서 index가 1인 모든 값을 0으로 삽입 
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [27]:
# tensor 합치기
t1 = torch.cat([tensor,tensor,tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [28]:
# tensor 곱하기
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# 다른 문법
print(f"tensor * tensor \n {tensor*tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [29]:
# 두 tensor 간의 행렬 곱(matrix multiplication)을 계산함.
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)}\n")
# 다른 문법
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [40]:
# 바꿔치기(in-place) 연산 : 접미사를 갖는 연산들은 바꿔치기(in-place) 연산입니다.
# ex) x.copy_()나 x.t_()는 x를 변경함.
print(tensor, "\n")
tensor.add_(5)
print(tensor)
tensor.copy_(tensor*tensor) # tensor 복사
print(tensor)
# 바꿔치기 연산은 메모리를 일부 절약하지만, 기록(history)이 즉시 삭제되어 도함수(derivative) 계산에 문제가 발생할 수 있습니다. 따라서 사용 권장 x

tensor([[2121., 2030., 2121., 2121.],
        [2121., 2030., 2121., 2121.],
        [2121., 2030., 2121., 2121.],
        [2121., 2030., 2121., 2121.]]) 

tensor([[2126., 2035., 2126., 2126.],
        [2126., 2035., 2126., 2126.],
        [2126., 2035., 2126., 2126.],
        [2126., 2035., 2126., 2126.]])
tensor([[4519876., 4141225., 4519876., 4519876.],
        [4519876., 4141225., 4519876., 4519876.],
        [4519876., 4141225., 4519876., 4519876.],
        [4519876., 4141225., 4519876., 4519876.]])
